name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  issue_comment:
    types: [created]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Assign pull requests to project
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: |
          github.event.action == 'opened' &&
          github.event_name == 'pull_request'
        with:
          project: "https://github.com/Thorium-Sim/thorium-nova/projects/1"
          column_name: "🧐 Review in progress"

      - name: Assign issues with `approved` label to project
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: |
          github.event_name == 'issues' &&
          contains(github.event.issue.labels.*.name, 'approved')
        with:
          project: "https://github.com/Thorium-Sim/thorium-nova/projects/1"
          column_name: "📌 Planned"
